//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public System.Guid Id { get; set; }
        public System.Guid StudentId { get; set; }
        public System.Guid CourseId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
